[package]
name = "trains-yew-svg"
version = "0.1.0"
authors = ["Magnus Hovland Hoff <maghoff@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.12.0"
wasm-bindgen = "0.2.58"
